#!/usr/bin/env python
import numpy as np
import subprocess
from os.path import expanduser

words = []
meanings = []
with open(expanduser("~") + "/.def/words.txt", "r") as f:
	for line in f:
		tmp = line.split("\t")
		tmp[-1] = tmp[-1].strip()
		words.append(tmp[0])
		meanings.append(tmp[1:])

practice_type = -1
print("Choice the practice type\n1. Test\n2. Free text\n")
practice_type = raw_input()
while (not str.isdigit(practice_type)) or int(practice_type) < 1 or int(practice_type) > 2:
	print("Please choose a valid option!")
	practice_type = raw_input()

practice_type = int(practice_type)

if practice_type == 1:
	n_opts = 5
	n_correct = 0
	n_false = 0
	inp = "y"
	subprocess.call("clear")
	while inp == 'y':
	    m_ind = np.random.randint(0, high=len(meanings))
	    aux = np.arange(len(words))
	    np.random.shuffle(aux)
	    w_ind = aux[:n_opts]

	    if m_ind not in w_ind:
		tmp = np.random.randint(0, high=n_opts)
		w_ind[tmp] = m_ind

	    print("Definition(s):")
	    for i in xrange(len(meanings[m_ind])):
		print(meanings[m_ind][i])

	    print("Options:")
	    for i in xrange(len(w_ind)):
		print(str(i) + ". " + words[w_ind[i]])
	    print("\nChoose the correct option: ")
	    inp = raw_input()
	    while (not str.isdigit(inp)) or not(0 <= int(inp) <= 4):
		print("Enter an integer between 0 and 4 inclusive")
		inp = raw_input()

	    if w_ind[int(inp)] == m_ind:
		print("Correct!\n")
		n_correct += 1
	    else:
		print("Wrong! The correct answer was " + words[m_ind] + "\n")
		n_false += 1

	    print("To continue, input y: ")
	    inp = raw_input()
	    subprocess.call("clear")

elif practice_type == 2:
	inp = 'y'
	n_correct = 0
	n_false = 0
	subprocess.call("clear")
	while inp == 'y':
		m_ind = np.random.randint(0, len(meanings))
		for i in range(len(meanings[m_ind])):
			print(meanings[m_ind][i])

		print("\nEnter the word:")
		answer = raw_input()

		if answer.lower() == words[m_ind].lower():
			print("Correct!")
			n_correct += 1
		else:
			print("Wrong! The answer was " + words[m_ind].lower())
			n_false += 1

		print("\n\nTo continue, input y: ")
		inp = raw_input()
		subprocess.call("clear")
    
print("Summary:\nNumber of correct answers: " + str(n_correct) + "\nNumber of false answers: " + str(n_false))
